<?xml version="1.0" encoding="utf-8"?><Database Name="BD_for_c#" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-ET4O128\SQLEXPRESS;Initial Catalog=BD_for_c#;Integrated Security=True" SettingsObjectName="WindowsFormsApp3.Properties.Settings" SettingsPropertyName="BD_for_c_ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.STUDENT" Member="STUDENTs">
    <Type Name="STUDENT">
      <Column Name="Stud_ID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Passport" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AD_ID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UN_AD_ID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="ADDRESS_STUDENT" Member="ADDRESS" ThisKey="AD_ID" OtherKey="AD_ID" Type="ADDRESS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ADDRESS" Member="ADDRESSes">
    <Type Name="ADDRESS">
      <Column Name="AD_ID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="ADDRESS_STUDENT" Member="STUDENTs" ThisKey="AD_ID" OtherKey="AD_ID" Type="STUDENT" />
    </Type>
  </Table>
</Database>